# Generated by Django 2.2.7 on 2023-04-28 15:11

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='إسم الشركة')),
                ('code', models.IntegerField(default=accounts.models.random_string, verbose_name='كود الشركة')),
                ('phone1', models.CharField(max_length=50, verbose_name='هاتف الشركة ')),
                ('phone2', models.CharField(max_length=50, verbose_name='إضافة رقم هاتف ثانى')),
                ('description', models.TextField(verbose_name='وصف الشركة')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('company_request', models.BooleanField(default=False, verbose_name='طلب شركة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
