# Generated by Django 2.2.7 on 2023-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230428_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_image',
            field=models.ImageField(blank=True, null=True, upload_to='Company_image', verbose_name='صورة الشركة'),
        ),
    ]
