# Generated by Django 2.2.7 on 2023-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='رقم الهاتف '),
            preserve_default=False,
        ),
    ]
