# Generated by Django 2.2.7 on 2023-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(blank=True, choices=[('شركة', 'شركة'), ('عميل', 'عميل')], default='عميل', max_length=50, null=True),
        ),
    ]
