# Generated by Django 3.2 on 2023-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230601_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(blank=True, choices=[('عميل', 'عميل'), ('شركة', 'شركة')], default='عميل', max_length=50, null=True),
        ),
    ]
