# Generated by Django 2.2.7 on 2023-04-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
    ]
