# Generated by Django 2.2.7 on 2023-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20230428_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
    ]
