# Generated by Django 2.2.7 on 2023-05-08 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230428_2313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0007_auto_20230428_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان الطلب ')),
                ('request_status', models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب ')),
                ('code', models.IntegerField(default=request.models.random_string, verbose_name='رقم الطلب')),
                ('description', models.TextField(verbose_name='وصف الطلب')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان الطلب ')),
                ('request_status', models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب ')),
                ('code', models.IntegerField(default=request.models.random_string, verbose_name='رقم الطلب')),
                ('description', models.TextField(verbose_name='وصف الطلب')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
