# Generated by Django 2.2.7 on 2023-05-09 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20230508_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('بناء', 'بناء'), ('ترميم', 'ترميم'), ('شراء ', 'شراء')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.TextField(max_length=500, verbose_name='حالة المرحلة ')),
                ('description', models.TextField(verbose_name='وصف المرحلة')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أخر تحديث للطلب')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('projectstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ProjectRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان الاجتماع')),
                ('description', models.TextField(verbose_name='موضوع الاجتماع')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أخر تحديث للطلب')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('meetings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ProjectRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts_Guarantees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.ImageField(upload_to=None, verbose_name='صورة العقد')),
                ('materials_used', models.ImageField(upload_to=None, verbose_name='المواد المستخدمة')),
                ('description', models.TextField(verbose_name='الضمنات')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='أخر تحديث للطلب')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('contracts_guarantees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ProjectRequest')),
            ],
        ),
    ]
