# Generated by Django 2.2.7 on 2023-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20230509_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='image_status',
            field=models.ImageField(default=1, upload_to=None, verbose_name='صورة للمرحلة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('شراء ', 'شراء'), ('بناء', 'بناء'), ('ترميم', 'ترميم')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
