# Generated by Django 2.2.7 on 2023-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_auto_20230509_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts_guarantees',
            old_name='request_status',
            new_name='image_status',
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('بناء', 'بناء'), ('ترميم', 'ترميم'), ('شراء ', 'شراء')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
    ]
