# Generated by Django 3.2 on 2023-05-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20230509_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationcomment',
            options={'verbose_name': 'Consultation Comment', 'verbose_name_plural': 'Consultation Comment'},
        ),
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'verbose_name': 'Consultation Request', 'verbose_name_plural': 'Consultation Request'},
        ),
        migrations.AlterModelOptions(
            name='contracts_guarantees',
            options={'verbose_name': 'Contracts Guarantees', 'verbose_name_plural': 'Contracts Guarantees'},
        ),
        migrations.AlterModelOptions(
            name='projectmeetings',
            options={'verbose_name': 'Project Meetings', 'verbose_name_plural': 'Project Meetings'},
        ),
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'verbose_name': 'Project Request', 'verbose_name_plural': 'Project Request'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Status'},
        ),
        migrations.RenameField(
            model_name='projectmeetings',
            old_name='meetings',
            new_name='project_meetings',
        ),
        migrations.RenameField(
            model_name='projectstatus',
            old_name='projectstatus',
            new_name='projectrequest',
        ),
        migrations.AddField(
            model_name='projectmeetings',
            name='meetingsLink',
            field=models.TextField(default=1, verbose_name='رابط الاجتماع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='contracts_guarantees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectmeetings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('بناء', 'بناء'), ('ترميم', 'ترميم'), ('شراء ', 'شراء')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('مرحلة تنظيف الأرض', 'مرحلة تنظيف الأرض'), ('الإنتهاء من البناء', 'الإنتهاء من البناء'), ('تسليم العمل', 'تسليم العمل'), ('مرحلة حفر الأساس', 'مرحلة حفر الأساس'), ('مرحلة البناء', 'مرحلة البناء'), ('مرحلة وضع البنية التحتية', 'مرحلة وضع البنية التحتية'), ('مرحلة إختيار الأرض', 'مرحلة إختيار الأرض'), ('مرحلة التشطيبات', 'مرحلة التشطيبات'), ('مرحلة تسليح الأساس', 'مرحلة تسليح الأساس')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
