# Generated by Django 3.2 on 2023-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20230521_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('ترميم', 'ترميم'), ('شراء ', 'شراء'), ('بناء', 'بناء')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('مرحلة حفر الأساس', 'مرحلة حفر الأساس'), ('استلام الارض', 'استلام الارض'), ('مرحلة تسليح الأساس', 'مرحلة تسليح الأساس'), ('مرحلة إختيار الأرض', 'مرحلة إختيار الأرض'), ('مرحلة وضع البنية التحتية', 'مرحلة وضع البنية التحتية'), ('مرحلة التشطيبات', 'مرحلة التشطيبات'), ('تسليم العمل', 'تسليم العمل'), ('مرحلة البناء', 'مرحلة البناء'), ('مرحلة تنظيف الأرض', 'مرحلة تنظيف الأرض'), ('الإنتهاء من البناء', 'الإنتهاء من البناء')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
