# Generated by Django 3.2 on 2023-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_auto_20230521_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('شراء ', 'شراء'), ('بناء', 'بناء'), ('ترميم', 'ترميم')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('مرحلة تسليح الأساس', 'مرحلة تسليح الأساس'), ('مرحلة البناء', 'مرحلة البناء'), ('استلام الارض', 'استلام الارض'), ('مرحلة التشطيبات', 'مرحلة التشطيبات'), ('مرحلة تنظيف الأرض', 'مرحلة تنظيف الأرض'), ('تسليم العمل', 'تسليم العمل'), ('مرحلة وضع البنية التحتية', 'مرحلة وضع البنية التحتية'), ('الإنتهاء من البناء', 'الإنتهاء من البناء'), ('مرحلة إختيار الأرض', 1), ('مرحلة حفر الأساس', 'مرحلة حفر الأساس')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
