# Generated by Django 3.2 on 2023-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_auto_20230521_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('مرحلة إختيار الأرض', 'A'), ('الإنتهاء من البناء', 'الإنتهاء من البناء'), ('مرحلة التشطيبات', 'مرحلة التشطيبات'), ('مرحلة البناء', 'مرحلة البناء'), ('مرحلة وضع البنية التحتية', 'مرحلة وضع البنية التحتية'), ('تسليم العمل', 'تسليم العمل'), ('مرحلة تنظيف الأرض', 'مرحلة تنظيف الأرض'), ('مرحلة تسليح الأساس', 'مرحلة تسليح الأساس'), ('مرحلة حفر الأساس', 'مرحلة حفر الأساس'), ('استلام الارض', 'استلام الارض')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
