# Generated by Django 3.2 on 2023-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_auto_20230521_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('مرحلة التشطيبات', 'مرحلة التشطيبات'), ('مرحلة البناء', 'مرحلة البناء'), ('استلام الارض', 'استلام الارض'), ('الإنتهاء من البناء', 'الإنتهاء من البناء'), ('تسليم العمل', 'تسليم العمل'), ('مرحلة وضع البنية التحتية', 'مرحلة وضع البنية التحتية'), ('مرحلة تسليح الأساس', 'مرحلة تسليح الأساس'), ('A', 'مرحلة إختيار الأرض'), ('مرحلة حفر الأساس', 'مرحلة حفر الأساس'), ('مرحلة تنظيف الأرض', 'مرحلة تنظيف الأرض')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
