# Generated by Django 3.2 on 2023-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_auto_20230521_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('7', 'مرحلة وضع البنية التحتية'), ('10', 'تسليم العمل'), ('5', 'مرحلة تسليح الأساس'), ('4', 'مرحلة حفر الأساس'), ('6', 'مرحلة البناء'), ('1', 'مرحلة إختيار الأرض'), ('2', 'استلام الارض'), ('9', 'الإنتهاء من البناء'), ('8', 'مرحلة التشطيبات'), ('3', 'مرحلة تنظيف الأرض')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
