# Generated by Django 3.2 on 2023-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_auto_20230521_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('شراء ', 'شراء'), ('بناء', 'بناء'), ('ترميم', 'ترميم')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[(9, 'الإنتهاء من البناء'), (8, 'مرحلة التشطيبات'), (4, 'مرحلة حفر الأساس'), (3, 'مرحلة تنظيف الأرض'), (10, 'تسليم العمل'), (7, 'مرحلة وضع البنية التحتية'), (2, 'استلام الارض'), (5, 'مرحلة تسليح الأساس'), (6, 'مرحلة البناء'), (1, 'مرحلة إختيار الأرض')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
