# Generated by Django 3.2 on 2023-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0033_auto_20230601_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مقبول', 'مقبول'), ('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('بناء', 'بناء'), ('شراء ', 'شراء'), ('ترميم', 'ترميم')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('10', 'تسليم العمل'), ('8', 'مرحلة التشطيبات'), ('5', 'مرحلة تسليح الأساس'), ('3', 'مرحلة تنظيف الأرض'), ('2', 'استلام الارض'), ('6', 'مرحلة البناء'), ('9', 'الإنتهاء من البناء'), ('4', 'مرحلة حفر الأساس'), ('1', 'مرحلة إختيار الأرض'), ('7', 'مرحلة وضع البنية التحتية')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
