# Generated by Django 3.2 on 2023-06-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_auto_20230601_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='contracts_guarantees',
            name='contracts_guarantees',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectmeetings',
            name='project_meetings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول'), ('مرفوض ', 'مرفوض')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='projectrequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('4', 'مرحلة حفر الأساس'), ('6', 'مرحلة البناء'), ('2', 'استلام الارض'), ('7', 'مرحلة وضع البنية التحتية'), ('8', 'مرحلة التشطيبات'), ('10', 'تسليم العمل'), ('9', 'الإنتهاء من البناء'), ('3', 'مرحلة تنظيف الأرض'), ('1', 'مرحلة إختيار الأرض'), ('5', 'مرحلة تسليح الأساس')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
