# Generated by Django 3.2 on 2023-06-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_auto_20230601_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('مرفوض ', 'مرفوض'), ('تحت المراجعة', 'تحت المراجعة'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='projectrequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('4', 'مرحلة حفر الأساس'), ('6', 'مرحلة البناء'), ('5', 'مرحلة تسليح الأساس'), ('9', 'الإنتهاء من البناء'), ('3', 'مرحلة تنظيف الأرض'), ('2', 'استلام الارض'), ('10', 'تسليم العمل'), ('7', 'مرحلة وضع البنية التحتية'), ('8', 'مرحلة التشطيبات'), ('1', 'مرحلة إختيار الأرض')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
