# Generated by Django 3.2 on 2023-06-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0036_auto_20230601_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='contracts_guarantees',
            name='contracts_guarantees',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_guarantees', to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectmeetings',
            name='project_meetings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_meetings', to='request.projectrequest'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='request_status',
            field=models.CharField(choices=[('تحت المراجعة', 'تحت المراجعة'), ('مرفوض ', 'مرفوض'), ('مقبول', 'مقبول')], default='تحت المراجعة', max_length=50, verbose_name='حالة الطلب '),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='workType',
            field=models.CharField(choices=[('ترميم', 'ترميم'), ('بناء', 'بناء'), ('شراء ', 'شراء')], default='بناء', max_length=50, verbose_name='نوع العمل '),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='request_status',
            field=models.CharField(choices=[('1', 'مرحلة إختيار الأرض'), ('7', 'مرحلة وضع البنية التحتية'), ('2', 'استلام الارض'), ('4', 'مرحلة حفر الأساس'), ('5', 'مرحلة تسليح الأساس'), ('3', 'مرحلة تنظيف الأرض'), ('6', 'مرحلة البناء'), ('8', 'مرحلة التشطيبات'), ('9', 'الإنتهاء من البناء'), ('10', 'تسليم العمل')], max_length=150, verbose_name='حالة المرحلة '),
        ),
    ]
